### ISSUE TITLE
Minimum Python version requirement for jitcxde

### ISSUE THREAD

**Issue by drsaroj** [neurophysik/jitcdde#19]

**Comment by drsaroj** [comment]
Please tell me the minimum version of python which current release of jitcxde support.

**Comment by Wrzlprmft** [comment]
It’s should be Python 3.3, though I haven’t tested that in quite a while (and I never tried earlier versions of Python 3). You can see this in the [setup.py](https://github.com/neurophysik/jitcxde_common/blob/master/setup.py). Usually you do not have to worry about this when installing with PIP or similar, since it will complain if requirements are not met.

Anyway, this is probably an [XY problem](https://en.wikipedia.org/wiki/XY_problem). Can you tell me why you want to know this?

**Comment by drsaroj** [comment]
Thank you for promt response. I am going to use these tools and if anything I need, I will disturb you for that since I am new to this.
