### ISSUE TITLE
Distributed delays?

### ISSUE THREAD

**Issue by uluzair** [neurophysik/jitcdde#2]
Great project, I am excited to see the final release!

By the way, do you plan to implement also (continuously) distributed delays?

**Comment by Wrzlprmft** [comment]
> By the way, do you plan to implement also (continuously) distributed delays?

Depending on what exactly you mean by this, this is already implemented.

For example, if you want a network where the delays between nodes are drawn from some distribution, but do not change over time, you can do this analogously to [this example for JiTCODE](http://jitcode.readthedocs.io/en/latest/#module-SW_of_Roesslers). Instead of using ω as a regular control parameter, you use it as the delay.

In general, if you can write down the DDE on paper using delay terms of the form y<sub>i</sub>(t-τ), you can integrate the system with JiTCDDE.

**Comment by uluzair** [comment]
All right, so the delays need to be discretized first. I guess this is straight-forward with systems of the kind

<a href="https://www.codecogs.com/eqnedit.php?latex=x'(t)=\int_{-\infty}^t&space;x(\sigma)&space;f(t-\sigma)d&space;\sigma" target="_blank"><img src="https://latex.codecogs.com/gif.latex?x'(t)=\int_{-\infty}^t&space;x(\sigma)&space;f(t-\sigma)d&space;\sigma" title="x'(t)=\int_{-\infty}^t x(\sigma) f(t-\sigma)d \sigma" /></a>

where f is a probability density function.

**Comment by Wrzlprmft** [comment]
> All right, so the delays need to be discretized first. I guess this is straight-forward with systems as for example

> <a href="https://www.codecogs.com/eqnedit.php?latex=x'(t)=\int_{-\infty}^t&space;x(\sigma)&space;f(t-\sigma)d&space;\sigma&space;-&space;x(t)^2" target="_blank"><img src="https://latex.codecogs.com/gif.latex?x'(t)=\int_{-\infty}^t&space;x(\sigma)&space;f(t-\sigma)d&space;\sigma&space;-&space;x(t)^2" title="x'(t)=\int_{-\infty}^t x(\sigma) f(t-\sigma)d \sigma - x(t)^2" /></a>

> where f is a positive function vanishing at infinity.

Yes, if you want to integrate such a system, you would have to discretise the integral beforehand. A numerical integrator would have to do something similar anyway, unless you want to integrate symbolically at each step – which would cost a lot of time and is probably very nasty to implement.

**Comment by Wrzlprmft** [comment]
FYI: I now implemented a utility function for integrals. More on Issue #11.
