### ISSUE TITLE
Problems with Initial Solutions

### ISSUE THREAD

**Issue by drsaroj** [neurophysik/jitcdde#22]
I have a query as to why the jitcdde solution is different than obtained by Mathematica NDSolve when it applies to the same problem with the same set of parameters and the same initial history function. 1a.jpeg and 1b.jpeg appear to be the same except the initial solution abound time=0. 
![1a](https://user-images.githubusercontent.com/47965452/57948911-8764c580-7900-11e9-80cd-d1254f90bbef.jpg)
![1b](https://user-images.githubusercontent.com/47965452/57948914-8a5fb600-7900-11e9-9153-29e8e1a61bba.jpeg)
[python.txt](https://github.com/neurophysik/jitcdde/files/3192664/python.txt)

**Comment by Wrzlprmft** [comment]
The reason is that `step_on_initial continuities` integrates the dynamics up to t=10. You then start integrating again from 0 to 10 (instead of starting at 0). Therefore the solutions you get here are extrapolated from the last step (i.e., from 10−ε to 10). (And yes, this should raise a warning.) If you really need the beginning, you have to use the output of several steps of `integrate_blindly`.
