### ISSUE TITLE
Using a delay as a control parameter

### ISSUE THREAD

**Issue by AlexSlow94** [neurophysik/jitcdde#28]
Hello,

First of all, I would like to thank you for this package, it's really amazing (even a beginner in programming like me can appreciate the lot of features and the way they are implemented).

I would like also to ask you a really quick question: can a delay parameter become a "control" parameter in the sense specified in the docs? I would like to sweep over it and try different delays.

(Actually, i would like to minimise the difference between my model and some data, fitting the model to them with a minimisation of residuals, but if it's possible to sweep over the delay parameter, I should do it).

I am talking about a "constant" delay, not a state-dependent delay nor a time-dependent delay.

**Comment by Wrzlprmft** [comment]
Yes, you can use control parameters as delays (or part of delays). However, be aware that:

* If you do this, you have all the disadvantages of state- or time-dependent delays, i.e. things are not as efficient and you have to specify a maximum delay. This is because JiTCDDE cannot know the value of the delay until you set it.
* The main advantage of using `control_pars` is that you save compilation time when doing frequent parameter changes and having big equations. In most cases, it is best to create a new `jitcdde` instance for every parameter value. I recommend that you only consider control parameters if you find yourself spending a considerable amount of time compiling.

> Actually, i would like to minimise the difference between my model and some data, fitting the model to them with a minimisation of residuals, but if it's possible to sweep over the delay parameter, I should do it

Note, that to find **local** minima, you can write a function that:

* takes your delay (and possibly other parameters) as an argument,
* performs a simulation with that delay
* computes the residual of the result
* returns the residual.

Then you can use this function as an argument for some minimiser like [`scipy.optimize.minimize`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.minimize.html). These do not care what happens into the function passed as an argument and are usually designed to reduce the number of calls to that function because it is typically the bottleneck.
