### ISSUE TITLE
Issue with C++ distribution

### ISSUE THREAD

**Issue by nwlandry** [neurophysik/jitcdde#32]
I'm reaching out about an issue I had when I tried to run the Mackey-Glass example code that you provided (I didn't modify your code at all). I downloaded Visual Studio Build Tools as suggested but I get the following error:

Generating, compiling, and loading C code.
jitced.c
C:\Program Files\Python38\include\pyconfig.h(59): fatal error C1083: Cannot open include file: 'io.h': No such file or directory
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.27.29110\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2

I am using a Windows machine and jitcdde-1.8.0.

Is there something that I am doing incorrectly? Here is a picture of the packages that I downloaded:
![image](https://user-images.githubusercontent.com/8760347/92644128-16d57b00-f2a0-11ea-9196-7d2ae4bc3a86.png)

I'd appreciate any help troubleshooting this.

**Comment by Wrzlprmft** [comment]
It will take a few days until I can properly look into this, so just a short comment: This appears to be an issue with building Python modules on Windows in general, so you may find answers elsewhere.

**Comment by Wrzlprmft** [comment]
It looks like this is due to some incomplete compiler installation on Windows – which is something I haven’t done in years. Please see [this Stack Overflow question](https://stackoverflow.com/q/40018405/2127008) as to whether it addresses your question. Either way, this problem does not appear to be specific to my module.
