### ISSUE TITLE
Example State-dependent delays?

### ISSUE THREAD

**Issue by MaikelBoss** [neurophysik/jitcdde#7]
It is stated that state-dependent delays should work. Is there a minimal example provided?

**Comment by Wrzlprmft** [comment]
No, there is no minimal example. So far, there was no demand for this and I haven’t looked into simple, well-posed examples. If you are aware of one, I will happily implement it.

However, usage is straightforward. Instead of `y(0,t-tau)` you just use for instance `y(0,t-tau*y(1))`.

Please keep in mind that the time-dependence of your delay should only change slowly. I haven’t intensively tested this, so if you encounter any issues, feel free to tell me.

**Comment by MaikelBoss** [comment]
The example I would like to implement is given by `y’(t)=-y(t-2-y(t)^2)+5` with initial condition given by `9/2 for t<-1` and `-1/2 for -1<=t<=0`

**Comment by Wrzlprmft** [comment]
Are you sure that’s what you want? I am asking because that DDE is rather boring and can be easily solved analytically. The initial delay is 9/4; thus the initial derivative is ẏ(0) = 19/2. As the delay is growing faster than the integration progresses, this will never change. Thus, your solution is y(t) = −1/2 + 19/2 t.

**Comment by MaikelBoss** [comment]
Sorry, there was a typo in the initial condition. I edited the post

**Comment by MaikelBoss** [comment]
Maybe I'm doing something wrong?  t=0 gives `y'(0)=-y(0-2-y(0)^2)+5=-y(-2-(-1/2)^2)+5=-9/2+10/2=1/2`

**Comment by Wrzlprmft** [comment]
Okay, [here](https://github.com/neurophysik/jitcdde/blob/master/examples/state_dependent.py) is an implementation of your problem.

As you will notice, there is a problem with the discontinuity in the past (at t=−1): If the delay term points to $t>−1$, it will be reduced by the dynamics, otherwise it will be increased. This means that the target of the delay will be attracted to $t=−1$ (yes, we have a dynamical system within a dynamical system). Now, with a discontinuity at $t=−1$, this is obviously a problem, as the behaviour of the DDE is not properly defined.

However, JiTCDDE doesn’t allow for implementing discontinuities in the first place – they can only be approximated by a sigmoid (whose steepness can be controlled by `eps` in the example code). As you can see, $y(t) ≈ \sqrt{t-1}$ for $t>1$, which means a constant delay target within the sigmoid.

**Comment by Wrzlprmft** [comment]
By the way: What is the motivation/source of this problem?

**Comment by MaikelBoss** [comment]
The example is from the book Introduction to the Theory and Application of Differential Equations with Deviating Arguments by S. B. Norkin L. E. El'sgol'ts
